### ISSUE TITLE
方法似乎有问题

### ISSUE THREAD

**Issue by icestarsss** [RManLuo/NP-FKGC#1]
您好，您的工作很有启发作用！
但您在GCN的过程中，分别考虑真实尾实体和候选节点的子图。由于候选节点数量比较多，所以候选节点的组合子图节点数量远超真实尾实体的子图。这导致了候选节点建模过程中受到了相当多的噪声，因此得分才显著下降。为了说明这一点，我用TransE代替了SManifoldE，令few=1，仅运行一个epoch时MRR就达到了0.53,。
![41c7b73aa75bde43b52b324e2fe6be5](https://github.com/RManLuo/NP-FKGC/assets/52323563/8680ffd8-a479-4410-a5b2-1ea1518ad3a6)
而当我进一步的将真实尾节点和候选节点组合在一起，考虑子图的时候，MRR并没有超过0.2。请您说明这点问题，谢谢

**Comment by RManLuo** [comment]
您好，感谢您对我们工作的兴趣。仅根据文字描述，我不能很好的理解您的问题，是否可以分享一下您的代码片段？如不方便，我们可以通过邮件进行讨论。

**Comment by RManLuo** [comment]
您好，在GNN卷积过程中，我们使用的是每个节点的2-hop邻居进行聚合，并生成向量表示。每个节点的聚合过程是独立的，并不会因为节点是query还是Negative导致聚合发生改变。但由于负样本数量较多，无法一次输入，所以我们先计算正例得分，然后再分batch计算负样本分数，最后一起进行排序。

**Comment by icestarsss** [comment]
因此严谨的做法应该是将query和negative一起输入，而这样您的结果将大幅降低。

**Comment by icestarsss** [comment]
先前的工作尽管是分开处理negative和query，但negative彼此之间没有干扰。但您的方法negative是DGL在背景知识图谱中采样邻域信息建模，所有negative在同一子图中，会有干扰信息。因此我认为在测试过程中，要么保证negative彼此独立，要么保证nagative和query在同一子图中。

**Comment by RManLuo** [comment]
请查看[DGL Neighbor Samping](https://docs.dgl.ai/guide/minibatch.html)。是以节点为中心构建领域子图，每个节点和其领域生成子图，不是所有输入节点构建子图。

**Comment by icestarsss** [comment]
感谢您的回复

**Comment by icestarsss** [comment]
感谢您的回复，我也需要进一步的研究
