### ISSUE TITLE
Questions about reproducibility

### ISSUE THREAD

**Issue by JusC-C** [RManLuo/NP-FKGC#8]
Dear Author, Thank you for your outstanding work. During the reproducibility process, even when using the provided checkpoint, I am unable to achieve the accuracy reported in the paper. Specifically, the MRR on the NELL dataset is 0.416.

**Comment by RManLuo** [comment]
Thanks for your interest in our work. Due to the randomness of sampling, it cannot get a fixed performance every time. Based on the current random seeds, it can usually get the report performance within 5 consecutive runs.

**Comment by JusC-C** [comment]
> Thanks for your interest in our work. Due to the randomness of sampling, it cannot get a fixed performance every time. Based on the current random seeds, it can usually get the report performance within 5 consecutive runs.

Thank you very much for your reply! So even when using the provided checkpoint, the reproducibility results may not align with those reported in the paper?

**Comment by RManLuo** [comment]
Performance was inconsistent across runs, but results were typically achieved within five consecutive attempts. We assume this is due to the random number generation under the given seeds.
